/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import persistencia.CadFunc;
import persistencia.CadProd;
import persistencia.DAOFunc;
import persistencia.DAOProd;

/**
 *
 * @author Wallace
 */
public class CadastroProdutos extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProdutos
     */
    public CadastroProdutos() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        cbxCategoria = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigodeBarras = new javax.swing.JTextField();
        ftfValor = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtCodigo.setEditable(false);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(20, 130, 240, 40);

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(270, 180, 420, 40);
        txtNome.setText("Nome:");
        txtNome.setFont(new Font("Century Ghotic", Font.ITALIC, 12));

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MemoriaRAM", "HD", "SSD", "SSD 2.0 NVME", "Monitor", "Gabinete", "Placa mãe", "Placa de Video", "Processador", "Mouse", "Teclado", " " }));
        getContentPane().add(cbxCategoria);
        cbxCategoria.setBounds(20, 230, 330, 30);

        btnSalvar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(20, 300, 330, 40);

        jLabel1.setText("VendasBNS | GESTÃO DE PRODUTOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 400, 30);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setText("Cadastro de Produtos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 410, 60);

        txtCodigodeBarras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigodeBarrasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigodeBarrasFocusLost(evt);
            }
        });
        getContentPane().add(txtCodigodeBarras);
        txtCodigodeBarras.setBounds(270, 130, 420, 40);
        txtCodigodeBarras.setText("Codigo de Barras:");
        txtCodigodeBarras.setFont(new Font("Century Ghotic", Font.ITALIC, 12));

        ftfValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.###"))));
        getContentPane().add(ftfValor);
        ftfValor.setBounds(20, 180, 240, 40);

        setSize(new java.awt.Dimension(761, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        CadProd prod;
        DAOProd dao;
        boolean retorno;
        
        //Pega a Data e  a Hora e envia para as variaveis data e hora
        Date dataHoraAtual = new Date();
        String data = new SimpleDateFormat("dd/MM/yyyy").format(dataHoraAtual);
        String hora = new SimpleDateFormat("HH:mm:ss").format(dataHoraAtual);

        if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Nome vazio!");
            txtNome.requestFocus();
        } else if (txtNome.getText().equals("Nome:")) {
            JOptionPane.showMessageDialog(null, "Campo Nome vazio!");
            txtNome.requestFocus();
        } else if (txtCodigodeBarras.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O Campo Codigo de barras vazio!");
            txtCodigodeBarras.requestFocus();
        } else if (txtCodigodeBarras.getText().equals("Codigo de Barras:")) {
            JOptionPane.showMessageDialog(null, "O Campo Codigo de barras vazio! Insira um valor valido.");
            txtCodigodeBarras.requestFocus();
        } else if (ftfValor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O Campo valor deve ser preenchido");
        } else {
            try {
                Integer.parseInt(txtCodigodeBarras.getText());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "O campo Codigo de Barras so aceita numeros\n " + e);
                txtCodigodeBarras.requestFocus();
            }

            prod = new CadProd();
            prod.setCodigo(txtCodigo.getText());
            prod.setNome(txtNome.getText());
            prod.setCodigodeBarras(txtCodigodeBarras.getText());
            prod.setCategoria(cbxCategoria.getSelectedItem().toString());
            prod.setValor("R$ " + ftfValor.getText());
            prod.setData(data);
            prod.setHora(hora);
            dao = new DAOProd();
            retorno = dao.conectar();
            if (retorno == true) {
                int r = dao.salvar(prod);
                if (r == 1) {
                    JOptionPane.showMessageDialog(null, "Cadastro Realizado!");

                }

            } else {
                JOptionPane.showMessageDialog(null, "Erro de conexão!! Contate o Administrador do programa. ");
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    // Auto complete para menssagems no campo
    private void txtCodigodeBarrasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigodeBarrasFocusGained
        if (txtCodigodeBarras.getText().equals("Codigo de Barras:")) {
            txtCodigodeBarras.setText("");
        }
    }//GEN-LAST:event_txtCodigodeBarrasFocusGained

    private void txtCodigodeBarrasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigodeBarrasFocusLost
        if (txtCodigodeBarras.getText().equals("")) {
            txtCodigodeBarras.setText("Codigo de Barras:");
            txtCodigodeBarras.setFont(new Font("Century Ghotic", Font.ITALIC, 12));

        }
    }//GEN-LAST:event_txtCodigodeBarrasFocusLost

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        if (txtNome.getText().equals("Nome:")) {
            txtNome.setText("");}    }//GEN-LAST:event_txtNomeFocusGained

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        if (txtNome.getText().equals("")) {
            txtNome.setText("Nome:");
            txtNome.setFont(new Font("Century Ghotic", Font.ITALIC, 12));
        }
    }//GEN-LAST:event_txtNomeFocusLost
  // Auto complete para menssagems no campo
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JFormattedTextField ftfValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigodeBarras;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
