/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Font;
import static java.awt.image.ImageObserver.WIDTH;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import persistencia.CadFunc;
import persistencia.CadProd;
import persistencia.DAOFunc;
import persistencia.DAOProd;

/**
 *
 * @author Wallace
 */
public class CadastroProdutos extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProdutos
     */
    public CadastroProdutos() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        cbxCategoria = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigodeBarras = new javax.swing.JTextField();
        ftfValor = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtCodigo.setEditable(false);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(20, 120, 240, 40);

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        getContentPane().add(txtNome);
        txtNome.setBounds(270, 190, 420, 40);
        txtNome.setText("Nome:");
        txtNome.setFont(new Font("Century Ghotic", Font.ITALIC, 12));

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o produto", "MemoriaRAM", "HD", "SSD", "SSD 2.0 NVME", "Monitor", "Gabinete", "Placa mãe", "Placa de Video", "Processador", "Mouse", "Teclado", " " }));
        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(cbxCategoria);
        cbxCategoria.setBounds(20, 250, 240, 30);

        btnSalvar.setBackground(new java.awt.Color(47, 174, 22));
        btnSalvar.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(20, 300, 330, 40);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setText("VendasBNS | GESTÃO DE PRODUTOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 0, 400, 40);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setText("Cadastro de Produtos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 410, 50);

        txtCodigodeBarras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigodeBarrasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigodeBarrasFocusLost(evt);
            }
        });
        getContentPane().add(txtCodigodeBarras);
        txtCodigodeBarras.setBounds(270, 120, 420, 40);
        txtCodigodeBarras.setText("Codigo de Barras:");
        txtCodigodeBarras.setFont(new Font("Century Ghotic", Font.ITALIC, 12));

        ftfValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.###"))));
        getContentPane().add(ftfValor);
        ftfValor.setBounds(20, 190, 240, 40);

        jButton2.setBackground(new java.awt.Color(51, 105, 248));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Voltar");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.white, java.awt.Color.white));
        jButton2.setBorderPainted(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(660, 10, 80, 23);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel11.setText("Quantidade de itens:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 170, 130, 14);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel12.setText("Código de barras:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(270, 100, 90, 14);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel13.setText("Nome:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(270, 170, 90, 14);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/assets/fund2.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-480, -10, 1320, 510);

        jMenu1.setText("Cadastro de Produtos");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/assets/outline_inventory_2_black_24dp.png"))); // NOI18N
        jMenuItem2.setText("Estoque");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/assets/outline_request_quote_black_24dp.png"))); // NOI18N
        jMenuItem3.setText("Fazer pedido");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/assets/logout.png"))); // NOI18N
        jMenuItem1.setText("Deslogar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/assets/power-off.png"))); // NOI18N
        jMenuItem4.setText("Fechar");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(761, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        CadProd prod;
        DAOProd dao;
        boolean retorno;
        
        //Pega a Data e  a Hora e envia para as variaveis data e hora
        Date dataHoraAtual = new Date();
        String data = new SimpleDateFormat("dd/MM/yyyy").format(dataHoraAtual);
        String hora = new SimpleDateFormat("HH:mm:ss").format(dataHoraAtual);

        if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Nome vazio!");
            txtNome.requestFocus();
        } else if (txtNome.getText().equals("Nome:")) {
            JOptionPane.showMessageDialog(null, "Campo Nome vazio!");
            txtNome.requestFocus();
        } else if (txtCodigodeBarras.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O Campo Codigo de barras vazio!");
            txtCodigodeBarras.requestFocus();
        } else if (txtCodigodeBarras.getText().equals("Codigo de Barras:")) {
            JOptionPane.showMessageDialog(null, "O Campo Codigo de barras vazio! Insira um valor valido.");
            txtCodigodeBarras.requestFocus();
        }
            else if (cbxCategoria.getSelectedItem().equals("Selecione o produto")) {
            JOptionPane.showMessageDialog(null, "Selecione um produto!", null, WIDTH); 
            cbxCategoria.requestFocus();
        }
        else if (ftfValor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O Campo valor deve ser preenchido");
        } else {
            try {
                Integer.parseInt(txtCodigodeBarras.getText());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "O campo Codigo de Barras so aceita numeros\n " + e);
                txtCodigodeBarras.requestFocus();
            }

            prod = new CadProd();
            prod.setCodigo(txtCodigo.getText());
            prod.setNome(txtNome.getText());
            prod.setCodigodeBarras(txtCodigodeBarras.getText());
            prod.setCategoria(cbxCategoria.getSelectedItem().toString());
            prod.setValor("R$ " + ftfValor.getText());
            prod.setData(data);
            prod.setHora(hora);
            dao = new DAOProd();
            retorno = dao.conectar();
            if (retorno == true) {
                int r = dao.salvar(prod);
                if (r == 1) {
                    JOptionPane.showMessageDialog(null, "Cadastro Realizado!");

                }

            } else {
                JOptionPane.showMessageDialog(null, "Erro de conexão!! Contate o Administrador do programa. ");
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    // Auto complete para menssagems no campo
    private void txtCodigodeBarrasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigodeBarrasFocusGained
        if (txtCodigodeBarras.getText().equals("Codigo de Barras:")) {
            txtCodigodeBarras.setText("");
        }
    }//GEN-LAST:event_txtCodigodeBarrasFocusGained

    private void txtCodigodeBarrasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigodeBarrasFocusLost
        if (txtCodigodeBarras.getText().equals("")) {
            txtCodigodeBarras.setText("Codigo de Barras:");
            txtCodigodeBarras.setFont(new Font("Century Ghotic", Font.ITALIC, 12));

        }
    }//GEN-LAST:event_txtCodigodeBarrasFocusLost

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        if (txtNome.getText().equals("Nome:")) {
            txtNome.setText("");}    }//GEN-LAST:event_txtNomeFocusGained

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        if (txtNome.getText().equals("")) {
            txtNome.setText("Nome:");
            txtNome.setFont(new Font("Century Ghotic", Font.ITALIC, 12));
        }
    }//GEN-LAST:event_txtNomeFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TelaInicial t = new TelaInicial();
        t.show();
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Cadastro_LoginBNS t = new Cadastro_LoginBNS();
        t.show();
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        Estoque est = new Estoque();
        est.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        VendasBNS t = new VendasBNS();
        t.show(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
  // Auto complete para menssagems no campo
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JFormattedTextField ftfValor;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigodeBarras;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
