/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.CadFunc;
import persistencia.DAOFunc;
import java.util.Scanner;

public class Estoque extends javax.swing.JFrame {

    /**
     * Creates new form Estoque
     */
    public Estoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        txtBuscAvançada = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProd = new javax.swing.JTable();
        btnMaisResult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 110, 110, 40);

        txtBuscAvançada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscAvançadaKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscAvançada);
        txtBuscAvançada.setBounds(480, 120, 240, 30);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(350, 120, 110, 30);

        jLabel1.setText("VendasBNS | GESTÃO DE PRODUTOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 400, 30);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel2.setText("Lista de produtos cadastrados");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 550, 60);

        jLabel3.setText("consulta avançada");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(610, 100, 110, 16);

        tblProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },

            new String [] {
                "codigo", "codigodebarras", "nome", "categoria", "data", "hora"
            }
        ));
        jScrollPane1.setViewportView(tblProd);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 710, 240);

        btnMaisResult.setText("Carregar mais resultados");
        getContentPane().add(btnMaisResult);
        btnMaisResult.setBounds(180, 410, 330, 40);

        setSize(new java.awt.Dimension(761, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            PreparedStatement st;
            Connection con;
            ResultSet rs;

            Class.forName("com.mysql.jdbc.Driver");

            String url = "jdbc:mysql://localhost:3306/vendasbns";
            String user = "root";
            String password = "WALL01101FfX7ss";

            con = DriverManager.getConnection(url, user, password);
            st = con.prepareStatement("SELECT * FROM produtos");
            rs = st.executeQuery();

            DefaultTableModel tblProduto = (DefaultTableModel) tblProd.getModel(); //Cria um modelo da tabela
            tblProduto.setNumRows(0);//Limpa as Linhas da tabela
            while (rs.next()) {//Enquanto tiver linhas no (rs) repita

                //Criar uma arrey (dados) que carrega os dados do rs
                Object[] dados = {rs.getString("codigo"), rs.getString("codigodebarras"), rs.getString("nome"),
                    rs.getString("categoria"),rs.getString("valor"), rs.getString("dataAt"), rs.getString("hora")};
                tblProduto.addRow(dados);//Adiciona os dados da arrey dados a uma row(linha)
            }
        } catch (ClassNotFoundException | SQLException ex) {

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscAvançadaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscAvançadaKeyReleased
         int teclado =+1;
        for(int i =0; i< teclado; i++){
            String busca = txtBuscAvançada.getText();
            pesquisaTxt(busca);
        }
    }//GEN-LAST:event_txtBuscAvançadaKeyReleased

     private void pesquisaTxt(String busca) {   
         
         try {
            PreparedStatement st;
            Connection con;
            ResultSet rs;

            Class.forName("com.mysql.jdbc.Driver");

            String url = "jdbc:mysql://localhost:3306/vendasbns";
            String user = "root";
            String password = "WALL01101FfX7ss";

            con = DriverManager.getConnection(url, user, password);
            st = con.prepareStatement("SELECT * FROM produtos WHERE nome LIKE'"+busca+"_%'");
            rs = st.executeQuery();

            DefaultTableModel tblProduto = (DefaultTableModel) tblProd.getModel(); //Cria um modelo da tabela
            tblProduto.setNumRows(0);//Limpa as Linhas da tabela
            while (rs.next()) {//Enquanto tiver linhas no (rs) repita

                //Criar uma arrey (dados) que carrega os dados do rs
                Object[] dados = {rs.getString("codigo"), rs.getString("codigodebarras"), rs.getString("nome"),
                    rs.getString("categoria"),rs.getString("valor"), rs.getString("dataAt"), rs.getString("hora")};
                tblProduto.addRow(dados);//Adiciona os dados da arrey dados a uma row(linha)
            }
        } catch (ClassNotFoundException | SQLException ex) {

        }
     }
    
    
    
    
/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estoque.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estoque.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estoque.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estoque.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMaisResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblProd;
    private javax.swing.JTextField txtBuscAvançada;
    // End of variables declaration//GEN-END:variables
}
