/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.Alterar;
import persistencia.DAOalterar;

/**
 *
 * @author Wallace
 */
public class TelaAlterar extends javax.swing.JFrame {

    private Estoque estoque = new Estoque();
    
    public TelaAlterar() {
//        initComponents();
//        carregarTxtBox();
//        carregarTabelaDadosTxt();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProd1 = new javax.swing.JTable();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCodigodeBarras = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        ftfValor = new javax.swing.JFormattedTextField();
        cbxCategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tblProd1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },

            new String [] {
                "codigo", "codigodebarras", "nome", "categoria", "data", "hora"
            }
        ));
        jScrollPane1.setViewportView(tblProd1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 730, 240);

        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigo.setText("Codigo:");
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(10, 30, 64, 22);

        txtNome.setText("Nome:");
        getContentPane().add(txtNome);
        txtNome.setBounds(10, 70, 270, 30);

        txtCodigodeBarras.setText("CodigodeBarras:");
        getContentPane().add(txtCodigodeBarras);
        txtCodigodeBarras.setBounds(300, 70, 270, 30);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(400, 170, 110, 40);

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(140, 170, 110, 40);

        btnDeletar.setText("Deletar");
        getContentPane().add(btnDeletar);
        btnDeletar.setBounds(270, 170, 110, 40);

        ftfValor.setText("Valor");
        getContentPane().add(ftfValor);
        ftfValor.setBounds(300, 110, 270, 30);

        cbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbxCategoria);
        cbxCategoria.setBounds(10, 110, 270, 30);

        setSize(new java.awt.Dimension(765, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void carregarTxtBox() {
        Alterar alt = new Alterar();
        // Carrega o codigo da consulta Tela estoque
        boolean retorno;
        DAOalterar dao = new DAOalterar();
        Alterar alter;

        int cod;
        cod = estoque.codiguin;

        retorno = dao.conectar();
        if (retorno) {
            alter = dao.consultar(cod);
            if (alter != null) {
                txtNome.setText(alter.getNome());
                txtCodigodeBarras.setText(alter.getCodigodeBarras());
                ftfValor.setText(alter.getValor());
                txtCodigo.setText(String.valueOf(alter.getCodigo()));
            } else {
//                JOptionPane.showMessageDialog(null, "Dados não carregados.");
            }
        }
    }

    private void alterar() {
        Date dataHoraAtual = new Date();
        String data = new SimpleDateFormat("dd/MM/yyyy").format(dataHoraAtual);
        String hora = new SimpleDateFormat("HH:mm:ss").format(dataHoraAtual);

        boolean retorno;
        DAOalterar dao;
        Alterar alter;

        alter = new Alterar();
        dao = new DAOalterar();
        retorno = dao.conectar();
        alter.setCodigo(Integer.parseInt(txtCodigo.getText()));
        alter.setNome(txtNome.getText());
        alter.setCodigodeBarras(txtCodigodeBarras.getText());
        alter.setCategoria(cbxCategoria.getSelectedItem().toString());
        alter.setValor(ftfValor.getText());
        alter.setDatadaAlteração("Data: " + data + " Hora: " + hora);
        retorno = dao.conectar();
        if (retorno == true) {
            int r = dao.alterar(alter);
            if (r == 1) {
                JOptionPane.showMessageDialog(null, "Cadastro Realizado!");

            }

        } else {
            JOptionPane.showMessageDialog(null, "Erro de conexão!! Contate o Administrador do programa. ");
        }
    }

    private void carregarTabelaDadosTxt() {

        DefaultTableModel tblProducts = (DefaultTableModel) tblProd1.getModel();

        txtCodigo.setText(tblProducts.getValueAt(tblProd1.getSelectedRow(), 0).toString());
        txtNome.setText(tblProducts.getValueAt(tblProd1.getSelectedRow(), 1).toString());
        txtCodigodeBarras.setText(tblProducts.getValueAt(tblProd1.getSelectedRow(), 2).toString());
        ftfValor.setText(tblProducts.getValueAt(tblProd1.getSelectedRow(), 3).toString());
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        alterar();
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JFormattedTextField ftfValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProd1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigodeBarras;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
